plugins {
    id 'fabric-loom' version "1.15-SNAPSHOT"
    id 'maven-publish'
}

base {
    archivesName = project.name
}

version = project.mod_version
group = project.maven_group

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        // add mod metadata
        expand "version": project.version , //"changelog_url": project.changelog_url,
                "curseforge_id": project.curseforge_id, "license": project.license_header,
                "mod_name": project.mod_name
    }
}

repositories {
    maven {
        name = "FabricMC"
        url = "https://maven.fabricmc.net"
    }
    maven {
        url = 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        url = 'https://maven.terraformersmc.com/releases'
        content {
            includeGroup 'com.terraformersmc'
        }
    }

    maven {
        name = 'Quilt'
        url = 'https://maven.quiltmc.org/repository/release'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "org.quiltmc:quilt-mappings:${minecraft_version}+build.${quilt_mappings}:intermediary-v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modRuntimeOnly ("com.terraformersmc:modmenu:${modmenu_version}") {
        exclude group: 'net.fabricmc.fabric-api'
        exclude group: 'net.fabricmc'
    }

//    modRuntime "curse.maven:mobz-336554:2826831"
//    modRuntime "curse.maven:carpet-349239:3542018"

    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
    compileOnly "org.jetbrains:annotations:19.0.0"
}


java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

publishing {
    publications {
        create("relocation", MavenPublication) {
            pom {
                // Old artifact coordinates
                groupId = "io.github.ladysnake"

                distributionManagement {
                    relocation {
                        // New artifact coordinates
                        groupId = "org.ladysnake"
                        message = "groupId has been changed"
                    }
                }
            }
        }
    }
}