# Dependencies: Visit https://lambdaurora.dev/tools/import_quilt.html and the Quilt Community Discord (https://discord.com/invite/M7GpuyTBvy) for dependency version info.
minecraft_version = 26.1
quilt_mappings = 23
loader_version=0.18.5

# NOTE: Comment out the line below if *not* using Fabric API.
fabric_version=0.144.4+26.1

# Base properties
mod_name = Creeper Spores
mod_version = 1.13.1
owners = Ladysnake
maven_group = org.ladysnake

#Other Dependencies
modmenu_version=11.0.4
#Publishing
license_header = LGPL
gpl_version = 3
modrinth_id = WSdgoMoj
curseforge_id = 331636
curseforge_versions = 1.20; 1.20.1
modrinth_versions = 1.20; 1.20.1
release_type = release

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs = -Xmx3G
